name: CI

# 当推送到main分支或创建PR时触发
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  # 代码质量检查
  lint-and-type-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3

    - name: 设置Node.js环境
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: 安装依赖
      run: npm ci

    - name: 类型检查
      run: npx tsc --noEmit

    - name: 代码格式检查
      run: npm run lint

    - name: 构建测试
      run: npm run build
      env:
        # 构建时提供测试环境变量
        DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        DEEPSEEK_BASE_URL: https://api.deepseek.com
        DEEPSEEK_MODEL: deepseek-chat
        API_TEMPERATURE: 0.7
        API_MAX_TOKENS: 200

  # 可选：API测试
  api-test:
    runs-on: ubuntu-latest
    needs: lint-and-type-check
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3

    - name: 设置Node.js环境
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: 安装依赖
      run: npm ci

    - name: 运行API测试
      run: node test-deepseek.js
      env:
        DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        DEEPSEEK_BASE_URL: https://api.deepseek.com 